export enum DoorState {
  UNLOCKED,
  LOCKED,
  DOORSTATE_FORCE_LOCKED_UNTIL_OUT_OF_AREA,
  DOORSTATE_FORCE_UNLOCKED_THIS_FRAME,
  DOORSTATE_FORCE_LOCKED_THIS_FRAME,
  DOORSTATE_FORCE_OPEN_THIS_FRAME,
  DOORSTATE_FORCE_CLOSED_THIS_FRAME,
}
